--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-certificate
  namespace: wordpress
spec:
  secretName: wordpress-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - montysplace.org
  - www.montysplace.org