---
kind: Namespace
apiVersion: v1
metadata:
  name: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: root-mysql-pass
  namespace: wordpress
type: Opaque
data:
  username: '<replace_with_base64_encoded_username>'
  password: '<replace_with_base64_encoded_password>'
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-mysql-pass
  namespace: wordpress
type: Opaque
data:
  username: '<replace_with_base64_encoded_username>'
  password: '<replace_with_base64_encoded_password>'
