apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend-expose
  namespace: longhorn-system
  labels:
    app: longhorn-frontend
spec:
  selector:
    app: longhorn-frontend
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 80
---
