apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-expose
  namespace: longhorn-system
  labels:
    app: longhorn-ui
spec:
  selector:
    app: longhorn-ui
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8000
---
