---
kind: Namespace
apiVersion: v1
metadata:
  name: wordpress-test
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: wordpress-test
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-test
  namespace: wordpress-test
  labels:
    app: wordpress
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wordpress-test
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0.27
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: root-mysql-pass
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: wp-mysql-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: "wordpress"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-test
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-test
        persistentVolumeClaim:
          claimName: mysql-pv-claim-test
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-external
  namespace: wordpress-test
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.86.203
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-test
  namespace: wordpress-test
  labels:
    app: wordpress
spec:
  storageClassName: nfs
  nfs:
    server: 192.168.86.76
    path: "/volume1/wordpressdata"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim-test
  namespace: wordpress-test
  labels:
    app: wordpress
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-test
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.8.2-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage-test
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage-test
        persistentVolumeClaim:
          claimName: wp-pv-claim-test
---
